package com.naqqa.outreach.engine;

import com.naqqa.outreach.config.OutreachProperties;
import com.naqqa.outreach.entity.LeadEntity;
import com.naqqa.outreach.entity.OutreachAccountStateEntity;
import com.naqqa.outreach.entity.OutreachProfileEntity;
import com.naqqa.outreach.entity.SendStatus;
import com.naqqa.outreach.entity.SentEmailEntity;
import com.naqqa.outreach.repository.SentEmailRepository;
import com.naqqa.outreach.service.BounceTracker;
import com.naqqa.outreach.service.DailyLimitService;
import com.naqqa.outreach.service.GmailSender;
import com.naqqa.outreach.service.LeadService;
import com.naqqa.outreach.service.OllamaClient;
import com.naqqa.outreach.service.OutreachLogService;
import com.naqqa.outreach.service.OutreachTime;
import com.naqqa.outreach.service.SafetyGates;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Sends AI-generated follow-ups as threaded replies (In-Reply-To the last message), levels 1..N with
 * configured day gaps. Only ~{@code followupRatio} (30%) of the daily cap goes to follow-ups; the
 * rest is left for new leads. The follow-up body is generated by the model from the WHOLE thread
 * history. Each lead is ONE row: a follow-up increments {@code followupCount} and is appended to the
 * row's {@code followups} history — no separate rows. A sequence stops once the lead replies /
 * bounces / unsubscribes (those records leave status SENT, so they're skipped here).
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class FollowupService {

    private final OutreachProperties props;
    private final SentEmailRepository sentRepo;
    private final GmailSender sender;
    private final SafetyGates gates;
    private final BounceTracker bounce;
    private final DailyLimitService limits;
    private final OllamaClient ollama;
    private final LeadService leads;
    private final OutreachLogService logService;

    public void dispatchDue(OutreachProfileEntity profile) {
        OutreachAccountStateEntity state = bounce.state(profile.getKey());
        limits.resetIfNewDay(state);
        int cap = limits.effectiveCap(profile, state);
        if (cap <= 0) {
            return;
        }

        // One candidate per thread. New data is already one row per thread; legacy data may still have
        // separate per-step rows — collapse them to the furthest-along row so we never double-send.
        Map<String, SentEmailEntity> byThread = new LinkedHashMap<>();
        for (SentEmailEntity s : sentRepo.findByProfileKeyAndStatus(profile.getKey(), SendStatus.SENT)) {
            byThread.merge(s.getThreadKey(), s, (a, b) -> progress(a) >= progress(b) ? a : b);
        }
        List<SentEmailEntity> candidates = new ArrayList<>(byThread.values());
        // Oldest-first so the longest-waiting leads get their follow-up first.
        candidates.sort(Comparator.comparing(SentEmailEntity::getLastActivity,
                Comparator.nullsLast(Comparator.naturalOrder())));

        // Follow-ups fill whatever the daily cap has left after initial sends — so when there are no
        // new leads to outreach, the day's capacity goes to 2nd/3rd emails for already-contacted
        // companies. The 30% follow-up floor is guaranteed by the engine capping initial sends.
        for (SentEmailEntity row : candidates) {
            if (state.getSentToday() >= cap
                    || !OutreachTime.isWorkingHours(props.getWorkStartHour(), props.getWorkEndHour())) {
                break;
            }
            if (!isDue(row)) {
                continue;
            }
            int level = progress(row) + 1; // next follow-up to send
            try {
                if (sendFollowup(profile, state, row, level)) {
                    Thread.sleep(ThreadLocalRandom.current().nextInt(
                            props.getMinDelaySeconds(), props.getMaxDelaySeconds() + 1) * 1000L);
                }
            } catch (InterruptedException ie) {
                Thread.currentThread().interrupt();
                return;
            } catch (Exception e) {
                log.warn("[{}] follow-up failed for {}: {}", profile.getKey(), row.getToEmail(), e.getMessage());
            }
        }
    }

    /** One-line-safe: strip newlines/quotes so a value can't break the send-log line format. */
    private String safe(String v) {
        return v == null ? "" : v.replaceAll("[\\r\\n\\t]+", " ").replace("\"", "'").trim();
    }

    /** "Subject" → "Re: Subject" (unless already a reply) so a follow-up reads as a reply. */
    private String reSubject(String subject) {
        String s = subject == null ? "" : subject.trim();
        return s.toLowerCase().startsWith("re:") ? s : "Re: " + s;
    }

    /** How many follow-ups this thread has already had — max of the new counter and legacy step. */
    private int progress(SentEmailEntity row) {
        return Math.max(row.getFollowupCount(), Math.max(0, row.getSequenceStep() - 1));
    }

    private boolean isDue(SentEmailEntity row) {
        // Never follow up a lead that has responded: a captured reply (any text) — on top of the
        // status filter, which already excludes RESPONDED / POSITIVE / NEGATIVE / UNSUBSCRIBED.
        if (row.getResponseText() != null && !row.getResponseText().isBlank()) {
            return false;
        }
        // Only follow up campaigns first sent on/after the cutoff — skip old/seeded/imported emails.
        java.time.LocalDate cutoff = props.getFollowupMinSentDate();
        if (cutoff != null) {
            java.time.Instant firstSent = row.getSentAt();
            if (firstSent == null || firstSent.isBefore(cutoff.atStartOfDay(java.time.ZoneOffset.UTC).toInstant())) {
                return false;
            }
        }
        int done = progress(row);
        Instant since = row.getLastActivity();
        if (done + 1 > props.getMaxFollowups() || since == null) {
            return false;
        }
        List<Integer> delays = props.getFollowupDelaysDays();
        int delayDays = delays.isEmpty() ? 3 : delays.get(Math.min(done, delays.size() - 1));
        return ChronoUnit.DAYS.between(since, Instant.now()) >= delayDays;
    }

    /** @return true if a follow-up was actually sent. */
    private boolean sendFollowup(OutreachProfileEntity profile, OutreachAccountStateEntity state,
                                 SentEmailEntity row, int level) throws Exception {
        // Full thread history, oldest first — initial email then every follow-up appended so far.
        List<OllamaClient.ThreadMessage> history = new ArrayList<>();
        history.add(new OllamaClient.ThreadMessage(1, row.getSubject(), row.getBody()));
        int step = 1;
        for (String prev : row.getFollowups()) {
            step++;
            history.add(new OllamaClient.ThreadMessage(step, reSubject(row.getSubject()), prev));
        }

        LeadEntity lead = leads.get(row.getCompanyId());
        List<String> companyInfo = lead != null && lead.getWebsiteInfo() != null && !lead.getWebsiteInfo().isBlank()
                ? List.of(lead.getWebsiteInfo()) : List.of();

        log.info("🤖 [{}] [AI] Generating follow-up #{} for {} ({})...", profile.getKey(),
                level, row.getCompanyName(), row.getToEmail());
        String body = ollama.generateFollowup(row.getCompanyName(), companyInfo, history, level);
        if (body == null || body.isBlank()) {
            log.info("⏭️ [{}] [AI] Follow-up #{} skipped for {} — empty generation.",
                    profile.getKey(), level, row.getToEmail());
            return false;
        }
        String subject = reSubject(row.getSubject()); // always a reply-style subject
        SafetyGates.Gate gate = gates.validateGeneratedEmail(subject, body, row.getCompanyName());
        if (!gate.valid()) {
            log.info("⏭️ [{}] [VALIDATE] Follow-up #{} failed safety gate ({}) for {}.",
                    profile.getKey(), level, gate.reason(), row.getToEmail());
            return false;
        }
        log.info("✉️ [{}] [GMAIL] Sending follow-up #{} → To: {} | Subject: {}", profile.getKey(),
                level, row.getToEmail(), subject);

        // Reply threaded onto the last message we sent (initial or previous follow-up).
        GmailSender.SendResult res = sender.send(profile, row.getToEmail(), subject, body, row.getMessageId());

        // Update the SAME row — no separate record: bump the count, append the body, re-thread.
        row.getFollowups().add(body);
        row.setFollowupCount(row.getFollowupCount() + 1);
        row.setInReplyTo(row.getMessageId());
        row.setMessageId(res.messageId());
        row.setLastSentAt(Instant.now());
        sentRepo.save(row);

        state.setSentToday(state.getSentToday() + 1);
        state.setFollowupsSentToday(state.getFollowupsSentToday() + 1);
        bounce.save(state);
        log.info("✅ [{}] [GMAIL] Follow-up #{} sent to {} ({}) — msgId={}",
                profile.getKey(), level, row.getToEmail(), row.getCompanyName(), res.messageId());
        logService.recordToStream(profile.getKey(), "sent", String.format(
                "FOLLOWUP #%d to=%s company=\"%s\" subject=\"%s\" msgId=%s",
                level, row.getToEmail(), safe(row.getCompanyName()), safe(subject), res.messageId()));
        return true;
    }
}
