package com.naqqa.outreach.engine;

import com.naqqa.outreach.config.OutreachProperties;
import com.naqqa.outreach.entity.LeadEntity;
import com.naqqa.outreach.entity.OutreachAccountStateEntity;
import com.naqqa.outreach.entity.OutreachProfileEntity;
import com.naqqa.outreach.entity.SendStatus;
import com.naqqa.outreach.entity.SentEmailEntity;
import com.naqqa.outreach.repository.SentEmailRepository;
import com.naqqa.outreach.service.BounceTracker;
import com.naqqa.outreach.service.DailyLimitService;
import com.naqqa.outreach.service.GmailSender;
import com.naqqa.outreach.service.LeadService;
import com.naqqa.outreach.service.OllamaClient;
import com.naqqa.outreach.service.OutreachTime;
import com.naqqa.outreach.service.SafetyGates;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Sends AI-generated follow-ups as threaded replies (In-Reply-To the last message), levels 1..N with
 * configured day gaps. Only ~{@code followupRatio} (30%) of the daily cap goes to follow-ups; the
 * rest is left for new leads. The follow-up body is generated by the model from the WHOLE thread
 * history. A sequence stops once the lead replies / bounces / unsubscribes (those records leave
 * status SENT, so they're skipped here).
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class FollowupService {

    private final OutreachProperties props;
    private final SentEmailRepository sentRepo;
    private final GmailSender sender;
    private final SafetyGates gates;
    private final BounceTracker bounce;
    private final DailyLimitService limits;
    private final OllamaClient ollama;
    private final LeadService leads;

    public void dispatchDue(OutreachProfileEntity profile) {
        OutreachAccountStateEntity state = bounce.state(profile.getKey());
        limits.resetIfNewDay(state);
        int cap = limits.effectiveCap(profile, state);
        if (cap <= 0) {
            return;
        }

        // Latest step per thread (only sequences still in SENT state are eligible), oldest-first.
        Map<String, SentEmailEntity> latest = new HashMap<>();
        for (SentEmailEntity s : sentRepo.findByProfileKeyAndStatus(profile.getKey(), SendStatus.SENT)) {
            latest.merge(s.getThreadKey(), s, (a, b) -> a.getSequenceStep() >= b.getSequenceStep() ? a : b);
        }
        List<SentEmailEntity> candidates = new ArrayList<>(latest.values());
        candidates.sort(Comparator.comparing(SentEmailEntity::getSentAt,
                Comparator.nullsLast(Comparator.naturalOrder())));

        // Follow-ups fill whatever the daily cap has left after initial sends — so when there are no
        // new leads to outreach, the day's capacity goes to 2nd/3rd emails for already-contacted
        // companies. The 30% follow-up floor is guaranteed by the engine capping initial sends.
        for (SentEmailEntity last : candidates) {
            if (state.getSentToday() >= cap
                    || !OutreachTime.isWorkingHours(props.getWorkStartHour(), props.getWorkEndHour())) {
                break;
            }
            if (!isDue(last)) {
                continue;
            }
            int level = last.getSequenceStep(); // step 1 sent → this becomes follow-up level 1
            try {
                if (sendFollowup(profile, state, last, level)) {
                    Thread.sleep(ThreadLocalRandom.current().nextInt(
                            props.getMinDelaySeconds(), props.getMaxDelaySeconds() + 1) * 1000L);
                }
            } catch (InterruptedException ie) {
                Thread.currentThread().interrupt();
                return;
            } catch (Exception e) {
                log.warn("[{}] follow-up failed for {}: {}", profile.getKey(), last.getToEmail(), e.getMessage());
            }
        }
    }

    /** "Subject" → "Re: Subject" (unless already a reply) so a follow-up reads as a reply. */
    private String reSubject(String subject) {
        String s = subject == null ? "" : subject.trim();
        return s.toLowerCase().startsWith("re:") ? s : "Re: " + s;
    }

    private boolean isDue(SentEmailEntity last) {
        int step = last.getSequenceStep();
        if (step > props.getMaxFollowups() || last.getSentAt() == null) {
            return false;
        }
        List<Integer> delays = props.getFollowupDelaysDays();
        int delayDays = delays.isEmpty() ? 3 : delays.get(Math.min(step - 1, delays.size() - 1));
        return ChronoUnit.DAYS.between(last.getSentAt(), Instant.now()) >= delayDays;
    }

    /** @return true if a follow-up was actually sent. */
    private boolean sendFollowup(OutreachProfileEntity profile, OutreachAccountStateEntity state,
                                 SentEmailEntity last, int level) throws Exception {
        // Full thread history, oldest first — the AI writes the reply from all previous messages.
        List<SentEmailEntity> thread = sentRepo.findByThreadKeyOrderBySequenceStepDesc(last.getThreadKey());
        List<OllamaClient.ThreadMessage> history = thread.stream()
                .sorted(Comparator.comparingInt(SentEmailEntity::getSequenceStep))
                .map(s -> new OllamaClient.ThreadMessage(s.getSequenceStep(), s.getSubject(), s.getBody()))
                .toList();

        LeadEntity lead = leads.get(last.getCompanyId());
        List<String> companyInfo = lead != null && lead.getWebsiteInfo() != null && !lead.getWebsiteInfo().isBlank()
                ? List.of(lead.getWebsiteInfo()) : List.of();

        String body = ollama.generateFollowup(last.getCompanyName(), companyInfo, history, level);
        if (body == null || body.isBlank()) {
            return false;
        }
        String subject = reSubject(last.getSubject()); // always a reply-style subject
        SafetyGates.Gate gate = gates.validateGeneratedEmail(subject, body, last.getCompanyName());
        if (!gate.valid()) {
            log.info("[{}] follow-up gate failed ({}) for {}", profile.getKey(), gate.reason(), last.getToEmail());
            return false;
        }

        GmailSender.SendResult res = sender.send(profile, last.getToEmail(), subject, body, last.getMessageId());

        SentEmailEntity next = new SentEmailEntity();
        next.setProfileKey(profile.getKey());
        next.setFromEmail(profile.getFromEmail());
        next.setCompanyId(last.getCompanyId());
        next.setCompanyName(last.getCompanyName());
        next.setToEmail(last.getToEmail());
        next.setToName(last.getToName());
        next.setWebsite(last.getWebsite());
        next.setCity(last.getCity());
        next.setSubject(subject);
        next.setBody(body);
        next.setSequenceStep(level + 1);
        next.setThreadKey(last.getThreadKey());
        next.setMessageId(res.messageId());
        next.setInReplyTo(last.getMessageId());
        next.setStatus(SendStatus.SENT);
        next.setSentAt(Instant.now());
        sentRepo.save(next);

        bounce.recordSent(state);
        state.setSentToday(state.getSentToday() + 1);
        state.setFollowupsSentToday(state.getFollowupsSentToday() + 1);
        bounce.save(state);
        log.info("[{}] sent AI follow-up level {} -> {} ({})",
                profile.getKey(), level, last.getToEmail(), last.getCompanyName());
        return true;
    }
}
