package com.naqqa.elasticsearch.script.painless;

public enum TokenType {
    NUMBER, STRING, REGEX, IDENTIFIER, KEYWORD,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    SEMI, COMMA, DOT, QDOT, COLON, ARROW, DOUBLE_COLON,
    PLUS, MINUS, STAR, SLASH, PERCENT,
    AMP, PIPE, CARET, TILDE, SHL, SHR, USHR,
    ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, STAR_ASSIGN, SLASH_ASSIGN, PERCENT_ASSIGN,
    AMP_ASSIGN, PIPE_ASSIGN, CARET_ASSIGN, SHL_ASSIGN, SHR_ASSIGN, USHR_ASSIGN, ELVIS_ASSIGN,
    EQ, NE, REF_EQ, REF_NE, LT, LE, GT, GE,
    AND, OR, NOT,
    INCR, DECR,
    QUESTION, ELVIS,
    MATCH, MATCHES,
    EOF
}
